apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: n8b5yv41i-nodejs
  janus-idp.io/tekton: n8b5yv41i-nodejs
  backstage.io/kubernetes-id: n8b5yv41i-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n8b5yv41i-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
