apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: n8b5yv41i-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: n8b5yv41i-nodejs 
  name: n8b5yv41i-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: n8b5yv41i-nodejs 
