apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: n8b5yv41i-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-46366d1af4.w9x1.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:cbcaeda473c66aa55ed15dcdd18a339900ab1019@sha256:0e84fc61462bcf9ad134262737e07f190242010a0af3bf881b3dc5722d8b4e24
          name: container-image
